create extension if not exists "uuid-ossp";

create table if not exists projects (
  id uuid primary key default uuid_generate_v4(),
  project_key text unique,
  name text not null,
  image_url text,
  address text,
  area numeric,
  company text,
  status text default 'ativo',
  start_date date,
  planned_end_date date,
  active_schedule_version_id uuid,
  baseline_schedule_version_id uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table projects add column if not exists city text;
alter table projects add column if not exists state text;
alter table projects add column if not exists ibge_code text;
alter table projects add column if not exists project_key text;
update projects set project_key = id::text where project_key is null or btrim(project_key) = '';
create unique index if not exists idx_projects_project_key on projects(project_key);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('project-images', 'project-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = true, file_size_limit = 5242880,
  allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];

drop policy if exists "public_project_images_read" on storage.objects;
create policy "public_project_images_read" on storage.objects for select using (bucket_id = 'project-images');
drop policy if exists "authenticated_project_images_insert" on storage.objects;
create policy "authenticated_project_images_insert" on storage.objects for insert to authenticated with check (bucket_id = 'project-images');
drop policy if exists "anon_project_images_insert" on storage.objects;
create policy "anon_project_images_insert" on storage.objects for insert to anon with check (bucket_id = 'project-images');

alter table projects enable row level security;
drop policy if exists "authenticated_projects_select" on projects;
create policy "authenticated_projects_select" on projects for select to authenticated using (true);
drop policy if exists "authenticated_projects_insert" on projects;
create policy "authenticated_projects_insert" on projects for insert to authenticated with check (true);
drop policy if exists "authenticated_projects_update" on projects;
create policy "authenticated_projects_update" on projects for update to authenticated using (true) with check (true);
drop policy if exists "public_projects_access" on projects;
create policy "public_projects_access" on projects for all to anon using (true) with check (true);

create table if not exists climate_cities (
  id uuid primary key default uuid_generate_v4(),
  name text not null unique,
  start_date date,
  end_date date,
  record_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table climate_cities add column if not exists start_date date;
alter table climate_cities add column if not exists end_date date;
alter table climate_cities add column if not exists record_count bigint not null default 0;

create table if not exists climate_records (
  id bigint generated by default as identity primary key,
  city_id uuid not null references climate_cities(id) on delete cascade,
  observation_date date not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_climate_records_city_date on climate_records(city_id, observation_date);

update climate_cities city
set start_date = summary.start_date,
    end_date = summary.end_date,
    record_count = summary.record_count
from (
  select city_id, min(observation_date) as start_date, max(observation_date) as end_date, count(*) as record_count
  from climate_records
  group by city_id
) summary
where city.id = summary.city_id;
alter table climate_cities enable row level security;
alter table climate_records enable row level security;
drop policy if exists "climate_cities_access" on climate_cities;
create policy "climate_cities_access" on climate_cities for all to anon, authenticated using (true) with check (true);
drop policy if exists "climate_records_access" on climate_records;
create policy "climate_records_access" on climate_records for all to anon, authenticated using (true) with check (true);

create table if not exists schedule_imports (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  file_name text not null,
  file_url text,
  file_type text,
  imported_at timestamptz default now(),
  detected_columns jsonb default '[]'::jsonb,
  mapping_config jsonb default '{}'::jsonb,
  row_count integer default 0,
  status text default 'importado'
);

create table if not exists schedule_versions (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  import_id uuid references schedule_imports(id) on delete set null,
  name text not null,
  type text default 'active',
  version_number integer default 0,
  source_version_id uuid references schedule_versions(id) on delete set null,
  is_active boolean default false,
  is_baseline boolean default false,
  created_at timestamptz default now(),
  notes text
);

create table if not exists lots (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  parent_lot_id uuid references lots(id) on delete cascade,
  name text not null,
  lot_type text,
  lot_order integer default 0,
  area numeric,
  weight_within_parent numeric default 100,
  active boolean default true
);

create table if not exists package_families (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  name text not null,
  default_color text,
  default_lane integer default 1,
  active boolean default true
);

create table if not exists packages (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  name text not null,
  short_name text,
  package_family_id uuid references package_families(id) on delete set null,
  color text,
  default_lane integer default 1,
  package_order integer default 0,
  procurement_type text default 'none',
  lead_time_days integer default 0,
  active boolean default true
);

create table if not exists schedule_tasks (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  project_key text,
  version_id uuid references schedule_versions(id) on delete cascade,
  external_id text,
  lot_mother text,
  lot text,
  package_name text,
  package_family text,
  service_name text,
  start_date date not null,
  end_date date not null,
  duration_days integer,
  quantity numeric,
  unit text,
  progress_percent numeric default 0,
  responsible_name text,
  team_name text,
  cost_estimated numeric,
  budget_code text,
  procurement_required boolean default false,
  status text default 'planejado',
  source text default 'import',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table schedule_tasks add column if not exists color text;
alter table schedule_tasks add column if not exists services jsonb default '[]'::jsonb;
alter table schedule_tasks add column if not exists predecessors jsonb default '[]'::jsonb;
alter table schedule_tasks add column if not exists successors jsonb default '[]'::jsonb;
alter table schedule_tasks add column if not exists lane integer;

alter table schedule_tasks enable row level security;
drop policy if exists "authenticated_schedule_tasks_select" on schedule_tasks;
create policy "authenticated_schedule_tasks_select" on schedule_tasks for select to authenticated using (true);
drop policy if exists "authenticated_schedule_tasks_insert" on schedule_tasks;
create policy "authenticated_schedule_tasks_insert" on schedule_tasks for insert to authenticated with check (true);
drop policy if exists "authenticated_schedule_tasks_update" on schedule_tasks;
create policy "authenticated_schedule_tasks_update" on schedule_tasks for update to authenticated using (true) with check (true);
drop policy if exists "public_schedule_tasks_access" on schedule_tasks;
create policy "public_schedule_tasks_access" on schedule_tasks for all to anon using (true) with check (true);

create table if not exists line_balance_settings (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  project_key text unique,
  version_id uuid references schedule_versions(id) on delete cascade,
  project_start_date date,
  default_zoom integer default 3,
  group_line_count jsonb default '{}'::jsonb,
  package_lane_map jsonb default '{}'::jsonb,
  package_family_lane_map jsonb default '{}'::jsonb,
  package_color_map jsonb default '{}'::jsonb,
  lot_order jsonb default '[]'::jsonb,
  show_milestones boolean default true,
  show_baseline boolean default true,
  show_dependencies boolean default true
);

alter table line_balance_settings add column if not exists payload jsonb default '{}'::jsonb;
alter table line_balance_settings add column if not exists updated_at timestamptz default now();

alter table line_balance_settings enable row level security;
drop policy if exists "authenticated_line_balance_settings_select" on line_balance_settings;
create policy "authenticated_line_balance_settings_select" on line_balance_settings for select to authenticated using (true);
drop policy if exists "authenticated_line_balance_settings_insert" on line_balance_settings;
create policy "authenticated_line_balance_settings_insert" on line_balance_settings for insert to authenticated with check (true);
drop policy if exists "authenticated_line_balance_settings_update" on line_balance_settings;
create policy "authenticated_line_balance_settings_update" on line_balance_settings for update to authenticated using (true) with check (true);
drop policy if exists "public_line_balance_settings_access" on line_balance_settings;
create policy "public_line_balance_settings_access" on line_balance_settings for all to anon using (true) with check (true);

create table if not exists milestones (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  version_id uuid references schedule_versions(id) on delete cascade,
  name text not null,
  date date not null,
  color text default '#b91c1c',
  show_on_line_balance boolean default true,
  description text
);

create table if not exists calendar_events (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  project_key text,
  date date not null,
  title text not null,
  kind text not null,
  color text not null,
  applies_to_all boolean default false,
  project_ids jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table calendar_events enable row level security;
drop policy if exists "authenticated_calendar_events_select" on calendar_events;
create policy "authenticated_calendar_events_select" on calendar_events for select to authenticated using (true);
drop policy if exists "authenticated_calendar_events_insert" on calendar_events;
create policy "authenticated_calendar_events_insert" on calendar_events for insert to authenticated with check (true);
drop policy if exists "authenticated_calendar_events_update" on calendar_events;
create policy "authenticated_calendar_events_update" on calendar_events for update to authenticated using (true) with check (true);
drop policy if exists "public_calendar_events_access" on calendar_events;
create policy "public_calendar_events_access" on calendar_events for all to anon using (true) with check (true);

create table if not exists schedule_dependencies (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  project_key text,
  version_id uuid references schedule_versions(id) on delete cascade,
  from_task_id uuid,
  to_task_id uuid,
  type text default 'FS',
  lag_days integer default 0,
  created_at timestamptz default now()
);

alter table schedule_dependencies alter column from_task_id type text using from_task_id::text;
alter table schedule_dependencies alter column to_task_id type text using to_task_id::text;

alter table schedule_dependencies enable row level security;
drop policy if exists "authenticated_schedule_dependencies_select" on schedule_dependencies;
create policy "authenticated_schedule_dependencies_select" on schedule_dependencies for select to authenticated using (true);
drop policy if exists "authenticated_schedule_dependencies_insert" on schedule_dependencies;
create policy "authenticated_schedule_dependencies_insert" on schedule_dependencies for insert to authenticated with check (true);
drop policy if exists "authenticated_schedule_dependencies_update" on schedule_dependencies;
create policy "authenticated_schedule_dependencies_update" on schedule_dependencies for update to authenticated using (true) with check (true);
drop policy if exists "public_schedule_dependencies_access" on schedule_dependencies;
create policy "public_schedule_dependencies_access" on schedule_dependencies for all to anon using (true) with check (true);

create table if not exists line_balance_versions (
  project_key text primary key,
  payload jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists schedule_saved_versions (
  id uuid primary key default uuid_generate_v4(),
  project_key text not null,
  name text not null,
  tasks jsonb not null default '[]'::jsonb,
  is_active boolean not null default false,
  is_baseline boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_schedule_saved_versions_project on schedule_saved_versions(project_key);
create unique index if not exists idx_schedule_saved_versions_active on schedule_saved_versions(project_key) where is_active;
create unique index if not exists idx_schedule_saved_versions_baseline on schedule_saved_versions(project_key) where is_baseline;
alter table schedule_saved_versions enable row level security;
drop policy if exists "authenticated_schedule_saved_versions_access" on schedule_saved_versions;
create policy "authenticated_schedule_saved_versions_access" on schedule_saved_versions for all to authenticated using (true) with check (true);
drop policy if exists "public_schedule_saved_versions_access" on schedule_saved_versions;
create policy "public_schedule_saved_versions_access" on schedule_saved_versions for all to anon using (true) with check (true);

alter table line_balance_versions enable row level security;
drop policy if exists "authenticated_line_balance_versions_select" on line_balance_versions;
create policy "authenticated_line_balance_versions_select" on line_balance_versions for select to authenticated using (true);
drop policy if exists "authenticated_line_balance_versions_insert" on line_balance_versions;
create policy "authenticated_line_balance_versions_insert" on line_balance_versions for insert to authenticated with check (true);
drop policy if exists "authenticated_line_balance_versions_update" on line_balance_versions;
create policy "authenticated_line_balance_versions_update" on line_balance_versions for update to authenticated using (true) with check (true);
drop policy if exists "public_line_balance_versions_access" on line_balance_versions;
create policy "public_line_balance_versions_access" on line_balance_versions for all to anon using (true) with check (true);

create table if not exists medium_plan_tasks (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  parent_schedule_task_id uuid,
  lot_path jsonb default '[]'::jsonb,
  package_name text,
  start_date date,
  end_date date,
  quantity numeric,
  productivity numeric,
  weight_within_parent numeric default 100,
  progress_percent numeric default 0
);

create table if not exists medium_plan_snapshots (
  project_key text primary key,
  payload jsonb not null default '[]'::jsonb,
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

alter table medium_plan_snapshots enable row level security;

drop policy if exists "authenticated_medium_plan_snapshots_select" on medium_plan_snapshots;
create policy "authenticated_medium_plan_snapshots_select" on medium_plan_snapshots
  for select to authenticated using (true);

drop policy if exists "authenticated_medium_plan_snapshots_insert" on medium_plan_snapshots;
create policy "authenticated_medium_plan_snapshots_insert" on medium_plan_snapshots
  for insert to authenticated with check (true);

drop policy if exists "authenticated_medium_plan_snapshots_update" on medium_plan_snapshots;
create policy "authenticated_medium_plan_snapshots_update" on medium_plan_snapshots
  for update to authenticated using (true) with check (true);
drop policy if exists "public_medium_plan_snapshots_access" on medium_plan_snapshots;
create policy "public_medium_plan_snapshots_access" on medium_plan_snapshots
  for all to anon using (true) with check (true);

create table if not exists medium_plan_windows (
  project_key text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

alter table medium_plan_windows enable row level security;

drop policy if exists "authenticated_medium_plan_windows_select" on medium_plan_windows;
create policy "authenticated_medium_plan_windows_select" on medium_plan_windows
  for select to authenticated using (true);

drop policy if exists "authenticated_medium_plan_windows_insert" on medium_plan_windows;
create policy "authenticated_medium_plan_windows_insert" on medium_plan_windows
  for insert to authenticated with check (true);

drop policy if exists "authenticated_medium_plan_windows_update" on medium_plan_windows;
create policy "authenticated_medium_plan_windows_update" on medium_plan_windows
  for update to authenticated using (true) with check (true);
drop policy if exists "public_medium_plan_windows_access" on medium_plan_windows;
create policy "public_medium_plan_windows_access" on medium_plan_windows
  for all to anon using (true) with check (true);

create table if not exists microservice_templates (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  package_family text not null,
  name text not null,
  active boolean default true
);

create table if not exists microservice_items (
  id uuid primary key default uuid_generate_v4(),
  template_id uuid references microservice_templates(id) on delete cascade,
  name text not null,
  weight_percent numeric not null,
  unit text,
  payment_criterion text,
  item_order integer default 0
);

create table if not exists weekly_plan_items (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  schedule_task_id uuid,
  medium_plan_task_id uuid,
  package_name text,
  microservice_name text,
  planned_quantity numeric,
  measured_quantity numeric,
  planned_percent numeric,
  measured_percent numeric,
  team_name text,
  failure_reason text,
  notes text
);

create table if not exists procurement_requirements (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  schedule_task_id uuid,
  package_name text,
  package_family text,
  budget_code text,
  item_code text,
  item_description text not null,
  required_quantity numeric not null default 0,
  unit text,
  estimated_unit_cost numeric,
  estimated_total_cost numeric,
  required_date date,
  lead_time_days integer default 0,
  deadline_to_request date,
  deadline_to_order date,
  source text default 'schedule'
);

create table if not exists procurement_external_lines (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  source_sheet text,
  budget_code text,
  request_number text,
  item_code text,
  item_description text,
  requested_quantity numeric default 0,
  converted_quantity numeric default 0,
  unit text,
  request_total_value numeric,
  required_date date,
  quote_number text,
  purchase_order_number text,
  supplier text,
  contract_number text,
  request_status text,
  order_status text,
  approval_status text
);

create table if not exists procurement_cards (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  item_code text,
  item_description text not null,
  package_name text,
  package_family text,
  required_quantity numeric default 0,
  requested_quantity numeric default 0,
  quoted_quantity numeric default 0,
  ordered_quantity numeric default 0,
  contracted_quantity numeric default 0,
  delivered_quantity numeric default 0,
  missing_quantity numeric default 0,
  coverage_percent numeric default 0,
  current_stage text default 'A programar',
  real_status text default 'Pendente',
  required_date date
);

create table if not exists budget_items (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  budget_code text,
  description text not null,
  quantity numeric,
  unit text,
  unit_cost numeric,
  total_cost numeric,
  cost_group text,
  contract_id text
);

create table if not exists financial_forecast (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  period date not null,
  planned_value numeric default 0,
  forecast_value numeric default 0,
  measured_value numeric default 0,
  accumulated_planned numeric default 0,
  accumulated_forecast numeric default 0,
  accumulated_measured numeric default 0
);

create table if not exists financial_lot_areas (
  project_key text not null references projects(project_key) on delete cascade,
  lot_mother text not null,
  lot_name text not null,
  projection_area numeric not null default 0 check (projection_area >= 0),
  updated_at timestamptz not null default now(),
  primary key (project_key, lot_mother, lot_name)
);
alter table financial_lot_areas enable row level security;
drop policy if exists "financial_lot_areas_access" on financial_lot_areas;
create policy "financial_lot_areas_access" on financial_lot_areas
  for all to anon, authenticated using (true) with check (true);

create table if not exists change_log (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid references projects(id) on delete cascade,
  module text not null,
  entity_type text not null,
  entity_id uuid,
  version_id uuid,
  field text,
  old_value jsonb,
  new_value jsonb,
  changed_at timestamptz default now(),
  reason text,
  source text default 'user'
);

create table if not exists short_term_state (
  project_key text primary key,
  payload jsonb not null default '{"weekly":[],"teams":[],"reasons":[],"history":[]}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

alter table short_term_state enable row level security;

drop policy if exists "authenticated_short_term_select" on short_term_state;
create policy "authenticated_short_term_select" on short_term_state
  for select to authenticated using (true);

drop policy if exists "authenticated_short_term_insert" on short_term_state;
create policy "authenticated_short_term_insert" on short_term_state
  for insert to authenticated with check (true);

drop policy if exists "authenticated_short_term_update" on short_term_state;
create policy "authenticated_short_term_update" on short_term_state
  for update to authenticated using (true) with check (true);

drop policy if exists "public_short_term_state_access" on short_term_state;
create policy "public_short_term_state_access" on short_term_state
  for all to anon using (true) with check (true);

create table if not exists app_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists budget_revisions (
  project_key text primary key,
  name text not null default 'Orçamento vigente',
  updated_at timestamptz not null default now()
);
alter table budget_revisions enable row level security;
drop policy if exists "budget_revisions_access" on budget_revisions;
create policy "budget_revisions_access" on budget_revisions for all to anon, authenticated using (true) with check (true);

create table if not exists financial_budgets (
  project_key text not null references projects(project_key) on delete cascade,
  type text not null check (type in ('contractor', 'financing')),
  name text not null,
  items jsonb not null default '[]'::jsonb,
  allocations jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (project_key, type)
);
alter table financial_budgets enable row level security;
drop policy if exists "financial_budgets_access" on financial_budgets;
create policy "financial_budgets_access" on financial_budgets
  for all to anon, authenticated using (true) with check (true);

-- Cada importação gera uma versão. Somente uma versão fica ativa por tipo,
-- mas versões anteriores, seus itens e vínculos permanecem para auditoria.
create table if not exists financial_budget_versions (
  id uuid primary key default uuid_generate_v4(),
  project_key text not null references projects(project_key) on delete cascade,
  budget_type text not null check (budget_type in ('contractor', 'financing')),
  version_number integer not null,
  name text not null,
  status text not null default 'active' check (status in ('draft', 'active', 'archived')),
  source_file_name text,
  source_file_hash text,
  eap_fingerprint text,
  header_row integer,
  mapping_config jsonb not null default '{}'::jsonb,
  import_summary jsonb not null default '{}'::jsonb,
  change_reason text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  activated_at timestamptz,
  archived_at timestamptz,
  unique (project_key, budget_type, version_number)
);
create unique index if not exists idx_financial_budget_active_version
  on financial_budget_versions(project_key, budget_type) where status = 'active';
create index if not exists idx_financial_budget_versions_history
  on financial_budget_versions(project_key, budget_type, version_number desc);

alter table financial_budgets add column if not exists active_version_id uuid
  references financial_budget_versions(id) on delete set null;

-- Itens e vínculos normalizados pertencem sempre a uma versão.
create table if not exists financial_budget_items (
  id uuid primary key default uuid_generate_v4(),
  version_id uuid not null references financial_budget_versions(id) on delete cascade,
  project_key text not null references projects(project_key) on delete cascade,
  budget_type text not null check (budget_type in ('contractor', 'financing')),
  level text,
  code text not null,
  description text not null,
  material_cost numeric not null default 0,
  labor_cost numeric not null default 0,
  total_cost numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (version_id, code)
);

create table if not exists financial_budget_allocations (
  id uuid primary key default uuid_generate_v4(),
  version_id uuid not null references financial_budget_versions(id) on delete cascade,
  project_key text not null references projects(project_key) on delete cascade,
  budget_type text not null check (budget_type in ('contractor', 'financing')),
  budget_item_id uuid not null references financial_budget_items(id) on delete cascade,
  schedule_task_external_id text not null,
  parent_schedule_task_external_id text,
  package_name text,
  service_name text,
  lot_name text,
  division_type text not null default 'manual'
    check (division_type in ('manual', 'equal', 'duration', 'quantity', 'area', 'percentage', 'inherited')),
  item_weight_percent numeric not null default 0
    check (item_weight_percent >= 0 and item_weight_percent <= 100),
  allocated_cost numeric not null default 0,
  inherited_from_allocation_id uuid references financial_budget_allocations(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (version_id, budget_item_id, schedule_task_external_id)
);

-- Migração idempotente para instalações que já possuíam itens/vínculos sem versão.
alter table financial_budget_items add column if not exists version_id uuid
  references financial_budget_versions(id) on delete cascade;
alter table financial_budget_allocations add column if not exists version_id uuid
  references financial_budget_versions(id) on delete cascade;
alter table financial_budget_allocations
  drop constraint if exists financial_budget_allocations_division_type_check;
alter table financial_budget_allocations
  add constraint financial_budget_allocations_division_type_check
  check (division_type in ('manual', 'equal', 'duration', 'quantity', 'area', 'percentage', 'inherited'));
insert into financial_budget_versions (
  project_key, budget_type, version_number, name, status, change_reason, activated_at
)
select budget.project_key, budget.type, 1, budget.name, 'active',
       'Versão inicial criada na migração do histórico', now()
from financial_budgets budget
where not exists (
  select 1 from financial_budget_versions version
  where version.project_key = budget.project_key and version.budget_type = budget.type
);
update financial_budget_items item
set version_id = version.id
from financial_budget_versions version
where item.version_id is null
  and version.project_key = item.project_key
  and version.budget_type = item.budget_type
  and version.status = 'active';
update financial_budget_allocations allocation
set version_id = version.id
from financial_budget_versions version
where allocation.version_id is null
  and version.project_key = allocation.project_key
  and version.budget_type = allocation.budget_type
  and version.status = 'active';
update financial_budgets budget
set active_version_id = version.id
from financial_budget_versions version
where budget.project_key = version.project_key
  and budget.type = version.budget_type
  and version.status = 'active'
  and budget.active_version_id is null;
alter table financial_budget_items alter column version_id set not null;
alter table financial_budget_allocations alter column version_id set not null;
alter table financial_budget_items
  drop constraint if exists financial_budget_items_project_key_budget_type_code_key;
alter table financial_budget_allocations
  drop constraint if exists financial_budget_allocations_project_key_budget_type_budget_item_id_schedule_task_external_id_key;
create unique index if not exists idx_financial_budget_item_version_code
  on financial_budget_items(version_id, code);
create unique index if not exists idx_financial_allocation_version_task
  on financial_budget_allocations(version_id, budget_item_id, schedule_task_external_id);

create index if not exists idx_financial_budget_items_project
  on financial_budget_items(project_key, budget_type, version_id);
create index if not exists idx_financial_allocations_task
  on financial_budget_allocations(project_key, version_id, schedule_task_external_id);
create index if not exists idx_financial_allocations_parent
  on financial_budget_allocations(project_key, parent_schedule_task_external_id);

alter table financial_budget_items enable row level security;
alter table financial_budget_allocations enable row level security;
alter table financial_budget_versions enable row level security;
drop policy if exists "financial_budget_versions_access" on financial_budget_versions;
create policy "financial_budget_versions_access" on financial_budget_versions
  for all to anon, authenticated using (true) with check (true);
drop policy if exists "financial_budget_items_access" on financial_budget_items;
create policy "financial_budget_items_access" on financial_budget_items
  for all to anon, authenticated using (true) with check (true);
drop policy if exists "financial_budget_allocations_access" on financial_budget_allocations;
create policy "financial_budget_allocations_access" on financial_budget_allocations
  for all to anon, authenticated using (true) with check (true);

-- Substitui todos os vínculos de uma versão em uma única transação.
-- Qualquer falha reverte também a exclusão, preservando os vínculos anteriores.
create or replace function public.replace_financial_budget_allocations(
  p_version_id uuid,
  p_project_key text,
  p_budget_type text,
  p_allocations jsonb
)
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  allocation_count integer := 0;
  payload jsonb := coalesce(p_allocations, '[]'::jsonb);
begin
  if jsonb_typeof(payload) <> 'array' then
    raise exception 'A lista de vínculos deve ser um array JSON.';
  end if;

  if not exists (
    select 1
    from financial_budget_versions
    where id = p_version_id
      and project_key = p_project_key
      and budget_type = p_budget_type
      and status = 'active'
  ) then
    raise exception 'A versão informada não é a versão ativa deste orçamento.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(payload) link
    left join financial_budget_items item
      on item.id = nullif(link->>'budgetId', '')::uuid
     and item.version_id = p_version_id
    where item.id is null
       or nullif(btrim(link->>'taskId'), '') is null
       or coalesce((link->>'weight')::numeric, -1) < 0
       or coalesce((link->>'weight')::numeric, 101) > 100
  ) then
    raise exception 'Há vínculos com item, atividade ou peso inválido.';
  end if;

  delete from financial_budget_allocations
  where version_id = p_version_id;

  insert into financial_budget_allocations (
    id, version_id, project_key, budget_type, budget_item_id,
    schedule_task_external_id, parent_schedule_task_external_id,
    package_name, service_name, lot_name, division_type,
    item_weight_percent, allocated_cost, inherited_from_allocation_id, updated_at
  )
  select
    coalesce(nullif(link->>'id', '')::uuid, uuid_generate_v4()),
    p_version_id,
    p_project_key,
    p_budget_type,
    (link->>'budgetId')::uuid,
    link->>'taskId',
    nullif(link->>'parentTaskId', ''),
    nullif(link->>'packageName', ''),
    nullif(link->>'serviceName', ''),
    nullif(link->>'lotName', ''),
    coalesce(nullif(link->>'divisionType', ''), 'manual'),
    (link->>'weight')::numeric,
    coalesce((link->>'value')::numeric, 0),
    nullif(link->>'inheritedFromId', '')::uuid,
    now()
  from jsonb_array_elements(payload) link;

  get diagnostics allocation_count = row_count;

  update financial_budgets
  set allocations = payload,
      updated_at = now()
  where project_key = p_project_key
    and type = p_budget_type
    and active_version_id = p_version_id;

  if not found then
    raise exception 'O orçamento ativo não foi encontrado para atualização.';
  end if;

  return allocation_count;
end;
$$;

grant execute on function public.replace_financial_budget_allocations(uuid, text, text, jsonb)
  to anon, authenticated;

create or replace function public.register_app_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.app_users (id, email) values (new.id, coalesce(new.email, ''))
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email on auth.users
for each row execute procedure public.register_app_user();

insert into public.app_users (id, email)
select id, coalesce(email, '') from auth.users
on conflict (id) do update set email = excluded.email;

alter table app_users enable row level security;
drop policy if exists "public_app_users_access" on app_users;
create policy "public_app_users_access" on app_users for select to anon, authenticated using (true);

create table if not exists user_project_access (
  user_id uuid not null references auth.users(id) on delete cascade,
  project_key text not null references projects(project_key) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, project_key)
);

alter table user_project_access enable row level security;
drop policy if exists "public_user_project_access" on user_project_access;
create policy "public_user_project_access" on user_project_access
  for all to anon, authenticated using (true) with check (true);

create index if not exists idx_schedule_tasks_project on schedule_tasks(project_id, version_id);
create unique index if not exists idx_schedule_tasks_project_external on schedule_tasks(project_key, external_id);
create index if not exists idx_procurement_cards_project on procurement_cards(project_id);
create index if not exists idx_change_log_project on change_log(project_id, changed_at desc);
